# Generated by Django 4.2.19 on 2025-04-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category_alter_auctionlisting_lister_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
    ]
