# Generated by Django 4.2.19 on 2025-04-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_language_auctionlisting_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='bids',
            field=models.IntegerField(default=0),
        ),
    ]
